name: cargo build/test/clippy

on: push

permissions:
  contents: read

jobs:
  linux-musl-arm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-musl
      - name: Install aarch64 musl build tools
        run: |
          sudo apt update
          sudo apt install -y musl-tools gcc-aarch64-linux-gnu
      - run: cargo build --target aarch64-unknown-linux-musl --release
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: -C target-feature=-crt-static
          CC_aarch64_unknown_linux_musl: aarch64-linux-gnu-gcc
